### ISSUE TITLE
Rotating the tree view

### ISSUE THREAD

**Issue by J-morag** [ShortestPathLab/posthoc-app#17]
Hello,

It would be useful to be able to rotate the tree view, so that it may better fit in its window (the tree might be very shallow and wide, or very deep and thin)

**Comment by francisanthony17** [comment]
008532c0f931530bda3e5e9162df2bba6cc92f1b

In this commit, we have added a dropdown feature where users are able to choose between a horizontal or vertical tree view

**Comment by J-morag** [comment]
Not that important, but why not a toggle button?

**Comment by Spaaaacccee** [comment]
Think the dropdown is fine for now, though a toggle button would eliminate the need to click twice.

**Comment by spaaaacccee** [comment]
In 79b81b740c3c655db8848e060e5d2e5d0b86a50f, the rotation button is a toggle button, and the view can be scaled, panned, and rotated.
