### ISSUE TITLE
Examples pane

### ISSUE THREAD

**Issue by dharabor** [ShortestPathLab/posthoc-app#39]
The welcome screen is great, showing all the available examples. Clicking one opens the example, but the welcome screen remains on top. It should disappear at this point, its job being finished.

Selecting the "Examples" view subsequently should re-open the welcome screen, instead of a panel. Suggest to get rid of examples-as-panel entirely.

**Comment by dharabor** [comment]
Related issue is the layout of the visualiser after the example is open. It's a bit messy. After some fiddling, I managed to produce a reasonably nice layout as per the attachment. Suggest a similar default after the example is loaded.

![Screenshot from 2024-03-10 15-27-16](https://github.com/path-visualiser/app/assets/2968372/876606a5-b498-4699-a630-049b29c4eab5)

**Comment by spaaaacccee** [comment]
In 79b81b740c3c655db8848e060e5d2e5d0b86a50f, the Explore panel could be reopened via the Maximise button on the top right corner panel. It's probably still useful to have the Explore panel as a sidebar, especially when we introduce tutorials and guides. Users may want to see them alongside their work.

<img width="260" alt="image" src="https://github.com/ShortestPathLab/posthoc-app/assets/15244945/0dc8fadb-5e4b-4817-a4ef-6f334e86633a">


Regarding default layout, please refer to #47.
