### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by dharabor** [ShortestPathLab/posthoc-app#42]
Running the Grid A* example takes quite a long time to finish the search. I have a few thoughts about this.

(1)  During playback we probably don't want to draw each individual event. We could simply draw the result of each expansion event. This would reduce the number of draw updates by quite a bit.

(2) Another way to jump ahead is to "expand in bulk"; i.e., show the result of expanding all nodes until the f-value increases. Then we could see the "f-layers", which is a pedagogical visualisation used to explain how search works to beginners (e.g., see FIT5222 Week 1 material on UCS). For practical reasons, these examples are usually small with details abstracted away. We could show them per instance!

(3) I notice the "Steps" panel scrolls during playback, suggesting we still write every event there but simply do not render it.  I propose we only keep an internal pointer of which event we're up to and then jump directly to that point when the playback stops. This change may require changing how we process the search trace (e.g., we may need to stream it incrementally).

**Comment by dharabor** [comment]
The StarCraft example is very slow. It seems to load 4 traces and one map and then proceeds to display everything, which takes quite a long time. 

Suggest we draw only the map and perhaps the initial state (the first event) of the first search trace. Hide the others by default.

**Comment by spaaaacccee** [comment]
In 79b81b740c3c655db8848e060e5d2e5d0b86a50f, we have several ways to jump ahead in the search, including setting up and stepping to breakpoints, increasing the playback speed, and navigating through steps in the search graph view. Through a compensation mechanism, the playback speed should be constant regardless of lag.  

In 39d333ec3e628b43ebb57c33dcbd0c8d58eb4170, we updated the default starcraft example to have 1 map and two traces (heat query and trace paths) for faster loading.
