### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by spaaaacccee** [ShortestPathLab/posthoc-app#44]
We need posthoc.pathfinding.ai to be a landing page to briefly introduce users to the mission, goals, features of the visualiser.

It doesn't have to be complicated, but it should have

- Description of the visualiser
- A link to the visualiser 
- A link to the docs
- List of contributors

**Comment by Spaaaacccee** [comment]
Concept landing page

![Image](https://github.com/path-visualiser/app/assets/15244945/45dbc4f2-a6e3-470e-927b-5cf772cc2b5a)

**Comment by Spaaaacccee** [comment]
![Image](https://github.com/path-visualiser/app/assets/15244945/039d6e09-ad99-4cd7-b219-61ede9543fff)

**Comment by spaaaacccee** [comment]
![image](https://github.com/ShortestPathLab/posthoc-app/assets/15244945/b7e794a0-b6e4-44c9-8d33-369747038899)
Implemented
